config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :achievements
    resources :achievement_criteria
    resources :endorsements
    resources :notes
    resources :simulated_days
    resources :skills
    resources :skill_ratings
    resources :votes

    root to: 'users#index'
  end

  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/graphql'
  end

  post '/graphql', to: 'graphql#execute'
  devise_for :users, controllers: { registrations: 'registrations' }

  authenticate :user do
    resources :users, except: [:show]
    resources :endorsements
    resources :relationships, only: [:create, :destroy]
    resources :skills
    resources :achievements do
      get 'grant'
    end
    resources :votes, only: [:destroy]
    resources :notes, except: [:show] do
      post 'upvote'
    end

    # After sign-up form
    get 'new-user/:id', to: 'users#new_user', as: :new_user_form

    # For the html importer
    get 'import/new', to: 'notes#new_import' # import_new_notes_path
    post 'import/new', to: 'notes#import' # import_notes_path

    get 'home', to: 'users#feed'
  end

  resources :notes, only: [:show]
  resources :users, only: [:show]

  authenticated :user do
    root 'users#feed', as: :authenticated_root
  end

  root 'home#index'

end

app/controllers/admin/notes_controller.rb
module Admin
  class NotesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Note.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Note.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  def new_import
    @note = Note.new
  end

  def import
    begin
      Note.sanitize_html(Note.import(params[:note][:import_file], current_user)).save
      redirect_to current_user
    rescue => exception
      redirect_to import_new_path, locals: exception
      end
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
    raise ActionController::RoutingError.new('Not Found') if (@note.is_private && @note.user != current_user)
    @endorsements = @note.sort_endorsements
    @buttons_visible = !current_user.blank?
    @upvote_btn = @note.should_show_upvote_btn(current_user)
    @vote = Vote.find_by(user_id: current_user.id, note_id: @note.id) unless current_user.blank?
  end

  # GET /notes/new
  def new
    @note = Note.new
    @skills = Skill.all.map(&:name)
  end

  # GET /notes/1/edit
  def edit
    @skills = Skill.all.map(&:name)
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)
    @note.user_id = current_user.id

    create_skills

    respond_to do |format|
      if @note.save
        format.html { redirect_to current_user }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    create_skills

    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to current_user }
      format.json { head :no_content }
    end
  end

  def upvote
    @note = Note.friendly.find(params[:note_id])
    Vote.create(note_id: @note.id, is_upvote?: true, user_id: current_user.id)
    redirect_to @note
  end

  private

  def create_skills
    skill_names = params[:note][:skills].split(',')
    return if skill_names == @note.skills.map(&:name) || skill_names.blank?
    @note.noteskills.destroy_all
    skill_names.each do |skill_name|
      ::Noteskill.create(note: @note, skill: Skill.find_by(name: skill_name))
    end
  end

  def set_note
    @note = Note.friendly.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:body, :title, :subtitle, :image_url, :comments_disabled, :is_private)
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_action_buttons.html.erb
<div class="mt-2">
  <% if @note.user == current_user  %>
    <%= link_to 'Edit', edit_note_path(@note),
                  method: :get,
                  class: 'btn btn-primary' %>
    <%= link_to 'Delete', note_path(@note),
                  method: :delete,
                  class: 'btn btn-danger note-delete-btn',
                  data: { confirm: 'This is non-reversible. Are you sure?'} %>
  <% end %>
</div>

app/views/notes/_buttons.html.erb
<div class="endorsement-container">
  <% note.skills.each do |skill| %>
    <span id="endorsement-form-<%= note.id %>-<%= skill.id %>">
      <% if note.user_endorsements.find_by(skill: skill, endorser: current_user).present? %>
        <%= render partial: 'notes/endorsed', 
          locals: {
            note: note,
            skill: skill,
            current_user: current_user,
            count: ::Endorsement.where(note: note, skill: skill, endorsee: note.user).count
          }
        %>
      <% else %>
        <%= render partial: 'notes/endorse', 
          locals: {
            note: note, 
            skill: skill, 
            current_user: current_user, 
            count: ::Endorsement.where(note: note, skill: skill, endorsee: note.user).count
          }
        %>
      <% end %>
    </span>
  <% end %>
</div>

app/views/notes/_comment.html.erb
<div class="comment-card my-3 p-3">
  <div class="comment-card-user-container">
    <%= link_to comment.user do %><img src="<%= comment.user.avatar_url %>" class="user-comment-avatar-img"/><% end %>
    <div>
      <%= link_to comment.user do %><div><%= comment.user.name %></div><% end %>
      <div class="note-date-container"><%= comment.created_at.strftime('%b %e') %></div>
    </div>
  </div>
  <div class="card-block mt-3"><%= comment.message %></div>
</div>

app/views/notes/_endorse.html.erb
<div class="endorse-container">
  <%= form_for(note.user_endorsements.build, remote: true, html: {id: "new-endorsement-#{skill.id}"}) do |form| %>
    <%= hidden_field_tag :endorser_id, current_user.id %>
    <%= hidden_field_tag :endorsee_id, note.user.id %>
    <%= hidden_field_tag :skill_id, skill.id %>
    <%= hidden_field_tag :note_id, note.id %>
    <%= hidden_field_tag :ajax, true %>
    <input class="skill-button endorse"
          type="image" 
          alt="<%= skill.name %>" 
          src="<%= skill.image_url %>" 
          name="commit" 
          value="<% skill.name %>" 
          class="btn btn-primary"
          data-disable-with="<%= skill.name %>"
          data-toggle="tooltip"
          data-placement="top"
          title="<%= skill.name %>"
          <%= note.user == current_user ? 'disabled' : '' %>>
  <% end %>
  <div class="flex-centered">
    <%= count %>
  </div>
</div>

app/views/notes/_endorsed.html.erb
<div class="endorse-container">
  <% if note.user_endorsements.find_by(skill: skill, endorser: current_user).present? %>
    <%= form_for(note.user_endorsements.find_by(skill: skill, endorser: current_user),
            html: { method: :delete },
            remote: true) do |form| %>
      <input class="skill-button unendorse"
            type="image" 
            alt="<%= skill.name %>" 
            src="<%= skill.image_url %>" 
            name="commit" 
            value="<%= skill.name %>" 
            class="btn btn-primary" 
            data-disable-with="<%= skill.name %>"
            data-toggle="tooltip"
            data-placement="top"
           title="<%= skill.name %>">
    <% end %>
  <% end %>
  <div class="flex-centered">
    <%= count %>
  </div>
</div>

app/views/notes/_form.html.erb
<div class="note-form">
  <%= bootstrap_form_for(note) do |f| %>
    <% if note.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(note.errors.count, 'error') %> prohibited this note from being saved:</h2>

        <ul>
        <% note.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.text_field :title %>
    </div>

    <div class="field">
      <%= f.text_field :subtitle %>
    </div>

    <%= f.label 'Image URL' %>
    <span class="fa fa-question-circle" title="This is the image that will be shown on the link to this article" data-toggle="tooltip" data-placement="top"></span>

    <div class="field">
      <%= f.text_field :image_url, hide_label: true %>
    </div>

    <div class="mt-4">
      What technologies are in this note?
      <%= text_field :note, :skills, id: 'skill-tags' %>
    </div>

    <div class="field note-new-body">
      <%= f.text_area :body %>
    </div>

    <div class="field">
      <%= f.check_box :comments_disabled %>
    </div>

    <div class="field">
      <%= f.check_box :is_private %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

<script>
  $(document).ready(function() {
      var s = <%= raw @skills.as_json %>;
      var skills = [];
      for (var i = 0; i < s.length; i++) {
          skills.push({skill: s[i]})
      }
      $('#skill-tags').selectize({
          maxItems: 3,
          create: false,
          persist: false,
          valueField: 'skill',
          labelField: 'skill',
          searchField: ['skill'],
          options: skills,
          items: <%= raw @note.skills.map(&:name).as_json %>
      });
  })
</script>

app/views/notes/_header.html.erb
<div class="row mt-5 mb-3">
  <div class="col-md">
    <div class="note-header-title">
      <h1 class="note-title"><%= @note.title %></h1>
      <%= render partial: 'subheader' %>
    </div>
  </div>
  <% if @note.image_url.present? %>
    <div class="col-md">
      <div class="image-header-frame" style="background-image: url('<%= @note.image_url %>');"></div>
    </div>
  <% end %>
</div>

app/views/notes/_subheader.html.erb
<div class="subheader-container">
  <%= link_to @note.user do %>
    <img src="<%= @note.user.avatar_url %>" class="note-user-avatar"/>
  <% end %>
  <div class="subheader-author-container">
    <div><%= @note.user.name %></div>
    <div><i><%= @note.created_at_display %></i></div>
  </div>
</div>

app/views/notes/edit.html.erb
<div class="container">
  <h1>Editing Note</h1>

  <%= render 'form', note: @note %>
</div>

app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.title %></td>
        <td><%= link_to 'Show', note %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<div class="container">
  <h1>New Note</h1>

  <%= render 'form', note: @note %>

  Or, use the <%= link_to 'html importer', import_new_path, method: :post %>
</div>

app/views/notes/new_import.html.erb
<div class="container">
  <h1 class="my-3">Import HTML Note</h1>
  <div class="row" style="margin-top: 5em;">
    <div class="col">
      <%= bootstrap_form_for @note, url: import_new_path, html: { multipart: true } do |f| %>

        <%= f.file_field :import_file, hide_label: true %>

        <%= f.submit %>

      <% end %>
    </div>

    <div class="col">
      <h3>Some Things to Consider:</h3>
      <ul>
        <li>This feature is in alpha - use at your own risk 😅</li>
        <li>The title is automatically generated from the name of the uploaded file.</li>
        <li>The text shown below the title on the note card on your profile is automatically generated from the first paragraph
          (defined as all the text before the first return or "\n" character).</li>
        <li>You will likely need to edit the note after importing for it to look normal</li>
      </ul>
    </div>
  </div>
</div>

app/views/notes/show.html.erb
<div class="container my-2">
  
  <%= render partial: 'header' %>

  <div class="centered my-2">
    <i><%= @note.subtitle %></i>
  </div>

  <div>
    <%= markdown @note.body %>
  </div>

  <% if @note.skills.present? %>
    <div class="endorse-description-container">
      <strong>Endorse <%= @note.user.name %> on one of the skills in this note:</strong>
      <%= render partial: 'buttons', locals: {note: @note, endorsements: @endorsements} %>
    </div>
  <% end %>

  <%= render partial: 'action_buttons' %>

  <% unless @note.comments_disabled %>
    <hr class="m-5">
    <div id="disqus_thread"></div>
    <script>
      var disqus_config = function () {
      this.page.url = "<%= request.original_url %>";  
      this.page.identifier = "<%= @note.slug %>"; 
      };
      (function() {
      var d = document, s = d.createElement('script');
      s.src = 'https://devsr.disqus.com/embed.js';
      s.setAttribute('data-timestamp', +new Date());
      (d.head || d.body).appendChild(s);
      })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <% end %>
</div>