config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :achievements
    resources :achievement_criteria
    resources :endorsements
    resources :notes
    resources :simulated_days
    resources :skills
    resources :skill_ratings
    resources :votes

    root to: 'users#index'
  end

  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/graphql'
  end

  post '/graphql', to: 'graphql#execute'
  devise_for :users, controllers: { registrations: 'registrations' }

  authenticate :user do
    resources :users, except: [:show]
    resources :endorsements
    resources :relationships, only: [:create, :destroy]
    resources :skills
    resources :achievements do
      get 'grant'
    end
    resources :votes, only: [:destroy]
    resources :notes, except: [:show] do
      post 'upvote'
    end

    # After sign-up form
    get 'new-user/:id', to: 'users#new_user', as: :new_user_form

    # For the html importer
    get 'import/new', to: 'notes#new_import' # import_new_notes_path
    post 'import/new', to: 'notes#import' # import_notes_path

    get 'home', to: 'users#feed'
  end

  resources :notes, only: [:show]
  resources :users, only: [:show]

  authenticated :user do
    root 'users#feed', as: :authenticated_root
  end

  root 'home#index'

end

app/models/skill.rb
# This model tracks the list of skills users can endorse eachother on.
class Skill < ApplicationRecord
  has_many :endorsements
  has_many :noteskills

  validates_presence_of :name
  validates_presence_of :image_url

  def notes
    self.noteskills.map(&:note)
  end
end

app/controllers/admin/skills_controller.rb
module Admin
  class SkillsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Skill.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Skill.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :set_skill, only: [:show, :edit, :update, :destroy]
  before_action :verify_user

  # GET /skills
  # GET /skills.json
  def index
    @skills = Skill.all
  end

  # GET /skills/1
  # GET /skills/1.json
  def show
  end

  # GET /skills/new
  def new
    @skill = Skill.new
  end

  # GET /skills/1/edit
  def edit
  end

  # POST /skills
  # POST /skills.json
  def create
    @skill = Skill.new(skill_params)

    respond_to do |format|
      if @skill.save
        format.html { redirect_to @skill }
        format.json { render :show, status: :created, location: @skill }
      else
        format.html { render :new }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /skills/1
  # PATCH/PUT /skills/1.json
  def update
    respond_to do |format|
      if @skill.update(skill_params)
        format.html { redirect_to @skill }
        format.json { render :show, status: :ok, location: @skill }
      else
        format.html { render :edit }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skills/1
  # DELETE /skills/1.json
  def destroy
    @skill.destroy
    respond_to do |format|
      format.html { redirect_to skills_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_skill
      @skill = Skill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def skill_params
      params.require(:skill).permit(:name, :description, :image_url)
    end

    def verify_user
      raise ActionController::RoutingError.new('Not Found') unless current_user.administrator?
    end
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/skills/_form.html.erb
<%= bootstrap_form_for(skill) do |f| %>
  <% if skill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(skill.errors.count, "error") %> prohibited this skill from being saved:</h2>

      <ul>
      <% skill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.text_field :image_url %>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/skills/edit.html.erb
<div class="container">
  <h1>Editing Skill</h1>
  <%= render 'form', skill: @skill %>
</div>

app/views/skills/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Skills</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @skills.each do |skill| %>
      <tr>
        <td><%= skill.name %></td>
        <td><%= skill.description %></td>
        <td><%= link_to 'Show', skill %></td>
        <td><%= link_to 'Edit', edit_skill_path(skill) %></td>
        <td><%= link_to 'Destroy', skill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Skill', new_skill_path %>

app/views/skills/new.html.erb
<div class="container">
  <h1>New Skill</h1>
  <%= render 'form', skill: @skill %>
</div>

app/views/skills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @skill.name %>
</p>

<p>
  <strong>Image:</strong><br>
  <img style="max-height: 100px" src="<%= @skill.image_url %>">
</p>

<p>
  <strong>Description:</strong>
  <%= @skill.description %>
</p>

<%= link_to 'Edit', edit_skill_path(@skill) %> |
<%= link_to 'Back', skills_path %>