config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :achievements
    resources :achievement_criteria
    resources :endorsements
    resources :notes
    resources :simulated_days
    resources :skills
    resources :skill_ratings
    resources :votes

    root to: 'users#index'
  end

  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/graphql'
  end

  post '/graphql', to: 'graphql#execute'
  devise_for :users, controllers: { registrations: 'registrations' }

  authenticate :user do
    resources :users, except: [:show]
    resources :endorsements
    resources :relationships, only: [:create, :destroy]
    resources :skills
    resources :achievements do
      get 'grant'
    end
    resources :votes, only: [:destroy]
    resources :notes, except: [:show] do
      post 'upvote'
    end

    # After sign-up form
    get 'new-user/:id', to: 'users#new_user', as: :new_user_form

    # For the html importer
    get 'import/new', to: 'notes#new_import' # import_new_notes_path
    post 'import/new', to: 'notes#import' # import_notes_path

    get 'home', to: 'users#feed'
  end

  resources :notes, only: [:show]
  resources :users, only: [:show]

  authenticated :user do
    root 'users#feed', as: :authenticated_root
  end

  root 'home#index'

end

app/models/achievement.rb
class Achievement < ApplicationRecord
  has_and_belongs_to_many :users
end

app/controllers/achievements_controller.rb
class AchievementsController < ApplicationController
  before_action :set_achievement, only: [:edit, :update, :destroy, :grant]
  before_action :verify_user

  # GET /achievements
  # GET /achievements.json
  def index
    @achievements = Achievement.all
  end

  # GET /achievements/new
  def new
    @achievement = Achievement.new
  end

  # GET /achievements/1/edit
  def edit
  end

  # POST /achievements
  # POST /achievements.json
  def create
    @achievement = Achievement.new(achievement_params)

    respond_to do |format|
      if @achievement.save
        format.html { rendirect_to achievements_url, notice: 'Achievement successfully saved.' }
        format.json { render json: @achievement.errors, status: :unprocessable_entity }
      else
        format.html { render :new }
        format.json { render json: @achievement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /achievements/1
  # PATCH/PUT /achievements/1.json
  def update
    granted = add_users

    respond_to do |format|
      if @achievement.update(achievement_params)
        format.html { redirect_to achievements_url, notice: "Achievement successfully #{granted ? 'granted.' : 'updated.'}" }
        format.json { render json: @achievement.errors, status: :unprocessable_entity }
      else
        format.html { render :edit }
        format.json { render json: @achievement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /achievements/1
  # DELETE /achievements/1.json
  def destroy
    @achievement.destroy
    respond_to do |format|
      format.html { redirect_to achievements_url, notice: 'Achievement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def grant
    @built_user = @achievement.users.build
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_achievement
      return @achievement = Achievement.find(params[:achievement_id]) if params[:achievement_id]
      @achievement = Achievement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def achievement_params
      params.fetch(:achievement, {})
    end

    def built_user_params
      params.require(:user).permit(id: [])
    end

    def add_users
      granted = false
      built_user_params[:id].each do |user_id|
        unless user_id.empty?
          u = User.find_by(id: user_id)
          if u.achievements.include? @achievement
            @achievement.users.delete(u)
          else
            @achievement.users << u
            granted = true
          end
        end
      end
      return granted
    end

    def verify_user
      raise ActionController::RoutingError.new('Not Found') unless current_user&.administrator?
    end
end

app/controllers/admin/achievements_controller.rb
module Admin
  class AchievementsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Achievement.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Achievement.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/helpers/achievements_helper.rb
module AchievementsHelper
end

app/views/achievements/_form.html.erb
<%= bootstrap_form_for(achievement) do |f| %>
  <% if achievement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(achievement.errors.count, "error") %> prohibited this achievement from being saved:</h2>

      <ul>
      <% achievement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_field :name %>

  <%= f.text_area :description %>

  <%= f.text_field :icon_name %>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/achievements/edit.html.erb
<div class="container">
  <h1>Editing Achievement</h1>

  <%= render 'form', achievement: @achievement %>

</div>

app/views/achievements/grant.html.erb
<div class="container">
  <%= form_for(@achievement) do |f| %>
    <%= fields_for(@built_user) do |built_user| %>
      <%= built_user.label 'Select users to give this achievement to:' %>
      <%= built_user.collection_select(:id, User.all.sort_by { |u| u.name }, :id, :name, {}, { multiple: true, class: 'form-control mb-2', id: 'grant-achievement-select' }) %>
    <% end %>
    <%= f.submit 'Grant', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/achievements/index.html.erb
<div class="container">
  <h1>Achievements</h1>

  <table>
    <thead>
      <tr>
        <th>Badge</th>
        <th>Name</th>
        <th>Description</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @achievements&.each do |achievement| %>
        <tr>
          <td><%= image_tag "badges/#{achievement.icon_name}" %></td>
          <td><%= achievement.name %></td>
          <td><%= achievement.description %></td>
          <td><%= link_to 'Grant', achievement_grant_path(achievement), class: 'btn btn-primary' %></td>
          <td><%= link_to 'Edit', edit_achievement_path(achievement), class: 'btn btn-secondary' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Achievement', new_achievement_path, class: 'btn btn-primary' %>
</div>

app/views/achievements/new.html.erb
<div class="container">
  <h1>New Achievement</h1>

  <%= render 'form', achievement: @achievement %>

</div>