config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :achievements
    resources :achievement_criteria
    resources :endorsements
    resources :notes
    resources :simulated_days
    resources :skills
    resources :skill_ratings
    resources :votes

    root to: 'users#index'
  end

  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/graphql'
  end

  post '/graphql', to: 'graphql#execute'
  devise_for :users, controllers: { registrations: 'registrations' }

  authenticate :user do
    resources :users, except: [:show]
    resources :endorsements
    resources :relationships, only: [:create, :destroy]
    resources :skills
    resources :achievements do
      get 'grant'
    end
    resources :votes, only: [:destroy]
    resources :notes, except: [:show] do
      post 'upvote'
    end

    # After sign-up form
    get 'new-user/:id', to: 'users#new_user', as: :new_user_form

    # For the html importer
    get 'import/new', to: 'notes#new_import' # import_new_notes_path
    post 'import/new', to: 'notes#import' # import_notes_path

    get 'home', to: 'users#feed'
  end

  resources :notes, only: [:show]
  resources :users, only: [:show]

  authenticated :user do
    root 'users#feed', as: :authenticated_root
  end

  root 'home#index'

end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_admin

    def authenticate_admin
      authorize! :manage, :admin_dashboard
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    def records_per_page
      params[:per_page] || 20
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {}

    extensions = {}

    text = ::Algorithms.format_code(text)
    
    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    text = markdown.render(text).gsub('<em>', '_').gsub('</em>', '_').html_safe
  end
end

app/views/application/_guest_navbar.html.erb
<nav class="topnav">
  <div class="topnav-left">
    <%= link_to root_path, id: 'navbar-logo', class: 'topnav-item' do %>
      DEV<span id="sr-secondary">SR</span>
    <% end %>
  </div>
  <div class="topnav-right" id="topnavResponsive">
    <span class="topnav-item"><%= render partial: 'session_buttons' %></span>
  </div>
</nav>

<div id="login-modal" class="modal fade" role="dialog">Y
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h2 class="modal-title">Log in</h2>
      </div>
      <div class="modal-body">
        <%= bootstrap_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
            <%= f.email_field :email, autofocus: true %>

            <%= f.password_field :password, autocomplete: 'off' %>

            <% if devise_mapping.rememberable? -%>
                <%= f.check_box :remember_me %>
            <% end -%>

            <div class="actions centered">
              <%= f.submit 'Log in', class: 'btn btn-primary' %>
            </div>
        <% end %>

        <%= render 'devise/shared/links' %>
      </div>
    </div>
  </div>
</div>

app/views/application/_navbar.html.erb
<% if user_signed_in? %>
  <%= render partial: 'signed_in_navbar' %>
<% else %>
  <%= render partial: 'guest_navbar' %>
<% end %>

app/views/application/_search_form.html.erb
<span>
  <%= form_tag(users_path, :method => 'get', id: 'search-form') do %>
    <div class="input-group">
      <%= text_field_tag :search, params[:search],
        id: 'search-input',
        placeholder: 'Search users',
        class: 'form-control',
        autocomplete: 'off',
        autocorrect: 'off',
        autocapitalize: 'off',
        spellcheck: 'false' %>
      <div class="input-group-btn">
        <%= button_tag :type => 'submit', :name => nil, class: 'btn btn-secondary', id: 'search-submit' do %>
          <%= icon('search') %>
        <% end %>
      </div>
    </div>
  <% end %>
</span>

app/views/application/_session_buttons.html.erb
<% unless user_signed_in?  %>
  <% unless params[:controller].eql?('devise/sessions') && params[:action].eql?('new') %>
    <button type="button" class="btn btn-primary round outline nav-link" id="sign-in-out-btn" data-toggle="modal" data-target="#login-modal">Log In</button>
  <% end %>
<% end %>
<% if user_signed_in? %>
  <%= link_to 'Log Out', destroy_user_session_path, class: 'btn btn-primary round outline nav-link', id: 'sign-in-out-btn', :method => :delete %>
<% end %>

app/views/application/_signed_in_navbar.html.erb
<nav class="topnav">
  <div class="topnav-left">
    <%= link_to root_path, id: 'navbar-logo', class: 'topnav-item' do %>
      DEV<span id="sr-secondary">SR</span>
    <% end %>
  </div>
  <div class="topnav-right" id="topnavResponsive">
    <span class="topnav-item"><%= link_to 'Home', home_path %></span>  
    <span class="topnav-item"><%= link_to 'Profile', user_path(current_user) %></span>
    <span class="topnav-item"><%= link_to 'Settings', edit_user_path(current_user) %></span>
    <span class="topnav-item"><%= render partial: 'search_form' %></span>
    <span class="topnav-item"><%= render partial: 'session_buttons' %></span>
  </div>
  <span class="icon" href="javascript:void(0);" onclick="mobileMenuOnClickHandler()">
    <i id="menuIconBars" class="fa fa-bars"></i>
    <i id="menuIconTimes" style="display:none;" class="fa fa-times"></i>
  </span>
</nav>

<div class="overlay" style="display:none;"></div>

<script>
    function mobileMenuOnClickHandler() {
        const overlay = $('.overlay');
        const topnav = document.getElementById("topnavResponsive");
        if (topnav.className === "topnav-right") {
            topnav.className = "topnav responsive";
        } else {
            topnav.className = "topnav-right";
        }
        
        const bars = $('#menuIconBars');
        const times = $('#menuIconTimes');
        bars.toggle();
        times.toggle();
        overlay.toggle();
    }
</script>